#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.axxies.blockstar.Resource", IsApplication=true)]

namespace com.axxies.blockstar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int flicker = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_left = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_right = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_screen_intro = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_options_off = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_options_on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_start_off = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_start_on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int intro_background = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int option_button = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int start_button = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int screen_intro = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int level_music_1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int level_music_10 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int level_music_2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int level_music_3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int level_music_4 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int level_music_5 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int level_music_6 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int level_music_7 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int level_music_8 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int level_music_9 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int menu_music = 2131034122;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
